Repository jenkins-x-labs/jenkins-x-versions, pull requests merged in 2020-04, with the labels that each got.

#58 fix: add kubernetes external secrets
  apps/external-secrets/kubernetes-external-secrets/defaults.yml
  charts/external-secrets/kubernetes-external-secrets.yml
  charts/repositories.yml
Labels: size/XS

#63 chore: test vault bdd
  README.md
  jx/bdd/vault/ci.sh
Labels: size/S

#70 fix: upgrade chart
  OWNERS
  charts/jenkins-x/jxboot-helmfile-resources.yml
Labels: approved, size/XS

#67 feat: add metrics-server
  apps/stable/metrics-server/defaults.yml
  charts/stable/metrics-server.yml
Labels: size/XS

#56 feat: add cluster-autoscaler
  apps/stable/cluster-autoscaler/defaults.yml
  apps/stable/cluster-autoscaler/values.yaml.gotmpl
  charts/stable/cluster-autoscaler.yml
Labels: size/S

#80 fix: upgrade chart
  charts/jenkins-x/jxboot-helmfile-resources.yml
Labels: approved, size/XS
