Repository jenkins-x-labs/jenkins-x-versions, pull requests merged in 2020-03, with the labels that each got.

#24 fix: use the right ServiceAccount names with jx helm3
  kubeProviders/eks/templates/irsa.tmpl.yaml
Labels: size/XS

#27 fix: correct indent of service.annotations
  apps/stable/nginx-ingress/values.yaml.gotmpl
Labels: size/XS

#33 fix: use correct helm 3 service name
  apps/stable/nginx-ingress/values.yaml.gotmpl
Labels: size/XS

#34 fix: external dns bindings
  apps/bitnami/external-dns/values.yaml.gotmpl
Labels: size/M

#37 chore: add workload identity annotation to tekton bot sa when on GKE
  apps/jenkins-x/tekton/values.yaml.gotmpl
Labels: size/XS

#45 fix: use the right variable to configure podSecurityContext
  apps/bitnami/external-dns/values.yaml.gotmpl
Labels: size/XS

#44 chore: upgrade jxboot-helmfile-resources
  charts/jenkins-x/jxboot-helmfile-resources.yml
Labels: size/XS

#38 fix: mount jenkins-docker-cfg to push images to AWS ECR
  apps/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
Labels: size/XS

#42 fix: use older version till postStart.sh is fixed for new version
  charts/jenkins-x/nexus.yml
Labels: size/XS

#41 fix: create SA using helm and use SA annotation for EKS
  apps/bitnami/external-dns/values.yaml.gotmpl
  apps/jenkins-x/jxui/values.yaml.gotmpl
  apps/jenkins-x/tekton/values.yaml.gotmpl
  apps/jetstack/cert-manager/values.yaml.gotmpl
Labels: approved, size/S
